spring:
  data:
    mongodb:
      host: localhost
      port: 27018
      database: products-db

  kafka:
    bootstrap-servers: localhost:9091

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
