spring:
  application:
    name: inventory-service

  data:
    mongodb:
      uri: mongodb://root:products@localhost:27018/orderflow?authSource=admin

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9999/.well-known/jwks.json

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8089

logging:
  level:
    org.apache.kafka: WARN
